const MIN_READER_WIDTH = 280
const MAX_READER_WIDTH = 600

/**
 * Bridges the additive `shell.overlay` slot to the host frame layout.
 * DSH renders overlays above its three-column frame. Reserving a fourth, empty
 * grid track makes the conversation and reader true peers while keeping the
 * overlay itself full width.
 *
 * Keeping the overlay full width is important in DSH Desktop compatibility and
 * extended modes: those modes make `[data-shell-overlay]` a transformed,
 * overflow-hidden containing block. The former width-based approach moved the
 * reader outside that block, so Electron showed only the black/transparent
 * native window material where the frame had been narrowed.
 */
export interface HostLayoutBridge {
  setReaderWidth: (width: number | null) => void
  dispose: () => void
}

export function createHostLayoutBridge(hostDocument: Document): HostLayoutBridge {
  let frame: HTMLElement | null = null
  let baseGridTemplate = ''
  let appliedGridTemplate = ''
  let originalTransition = ''
  let readerWidth = 0
  let observer: MutationObserver | null = null

  const restore = (): void => {
    if (frame === null) return
    observer?.disconnect()
    observer = null
    frame.style.gridTemplateColumns = baseGridTemplate
    frame.style.transition = originalTransition
    frame.removeAttribute('data-dnr-reader-layout')
    frame = null
    appliedGridTemplate = ''
  }

  const applyReaderTrack = (): void => {
    if (frame === null || baseGridTemplate.trim().length === 0) return
    appliedGridTemplate = `${baseGridTemplate} ${readerWidth}px`
    if (frame.style.gridTemplateColumns !== appliedGridTemplate) {
      frame.style.gridTemplateColumns = appliedGridTemplate
    }
    frame.style.transition = [originalTransition, 'grid-template-columns 180ms cubic-bezier(.2,.8,.2,1)']
      .filter(Boolean)
      .join(', ')
    frame.setAttribute('data-dnr-reader-layout', readerWidth > 0 ? 'open' : 'closed')
  }

  const attach = (nextFrame: HTMLElement): void => {
    if (nextFrame === frame) return
    restore()
    frame = nextFrame
    baseGridTemplate = frame.style.gridTemplateColumns
    originalTransition = frame.style.transition

    const MutationObserverCtor = hostDocument.defaultView?.MutationObserver
    if (MutationObserverCtor !== undefined) {
      observer = new MutationObserverCtor(() => {
        if (frame === null) return
        const hostTemplate = frame.style.gridTemplateColumns
        // Ignore the mutation generated by applyReaderTrack itself. Any other
        // template is a host re-render (resize/sidebar/details change), and
        // becomes the new three-column base before the reader track is restored.
        if (hostTemplate === appliedGridTemplate) return
        baseGridTemplate = hostTemplate
        applyReaderTrack()
      })
      observer.observe(frame, { attributes: true, attributeFilter: ['style'] })
    }
  }

  const setReaderWidth = (width: number | null): void => {
    const overlay = hostDocument.querySelector<HTMLElement>('[data-shell-overlay]')
    const nextFrame = overlay?.parentElement ?? null
    if (nextFrame === null) return
    attach(nextFrame)

    readerWidth = width === null
      ? 0
      : Math.min(MAX_READER_WIDTH, Math.max(MIN_READER_WIDTH, Math.round(width)))
    applyReaderTrack()
  }

  return { setReaderWidth, dispose: restore }
}
